{{- if and .Values.managedIdentityName .Values.managedIdentityClientId }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.managedIdentityName }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.managedIdentityClientId }}"
{{- end }}