# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scan Terraform code

on:
  push:
    branches: 
      - main
    paths:
      - "infra/terraform/**"
  pull_request:
    branches: 
      - main
    paths:
      - "infra/terraform/**"
  workflow_dispatch:

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Run Trivy vulnerability scanner in IaC mode for Terraform
        uses: aquasecurity/trivy-action@b2933f565dbc598b29947660e66259e3c7bc8561 # 0.20.0
        with:
          scan-type: 'config'
          scan-ref: './infra/terraform'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-terraform-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@e14ec90e52a057614c707baecf2ed88a81b68bc9 # v2
        with:
          sarif_file: 'trivy-terraform-results.sarif'
